Database Connection

In [1]:
import os

import numpy as np
from dotenv import load_dotenv, find_dotenv
from sqlalchemy import create_engine
from sqlalchemy.exc import SQLAlchemyError

load_dotenv(find_dotenv())

def connect_to_db():
    host = os.getenv("DB_HOST", "localhost")
    port = os.getenv("DB_PORT", "5432")
    database = os.getenv("DB_NAME")
    user = os.getenv("DB_USER")
    password = os.getenv("DB_PASSWORD")

    if not all([database, user, password]):
        print("Σφάλμα: Δεν βρέθηκαν οι απαραίτητες μεταβλητές στο .env!")
        return None

    try:
        connection_uri = f"postgresql://{user}:{password}@{host}:{port}/{database}"
        engine = create_engine(connection_uri)
        with engine.connect() as connection:
            print(f"Επιτυχής σύνδεση στη βάση '{database}' στο host '{host}'!")
        return engine

    except SQLAlchemyError as e:
        print(f"Σφάλμα κατά τη σύνδεση στη ΒΔ: {e}")
        return None


print("Εκκίνηση σύνδεσης με τη βάση...")
engine = connect_to_db()

if engine is None:
    print("Τερματισμός προγράμματος λόγω αποτυχίας σύνδεσης.")
    exit(1)

Εκκίνηση σύνδεσης με τη βάση...
Επιτυχής σύνδεση στη βάση 'thesis_db' στο host 'dell-micro'!

Import data to dataframe

In [2]:
import pandas as pd

query = "SELECT match_id, x_loc, y_loc, distance_to_goal, angle_to_goal, is_goal FROM understat_shots_normalized"
us_shots = pd.read_sql(query, con=engine)


query = "SELECT match_id, x_loc, y_loc, distance_to_goal, angle_to_goal, is_goal FROM statsbomb_shots_normalized"
sb_shots = pd.read_sql(query, con=engine)

Remove overlapping matches

In [3]:
query = "SELECT understat_match_id FROM mapping_overlapping_matches"
overlapping_matches = pd.read_sql_query(query, con=engine)
overlapping_matches.head()

   understat_match_id
0                 923
1                 662
2                 727
3                 890
4                 644

In [4]:
print(f"Αρχικές εγγραφές us_shots: {len(us_shots)}")
overlapping_matches_list = overlapping_matches['understat_match_id'].unique()

# Αφαίρεση overlapping matches από το us_shots
us_shots = us_shots[~us_shots['match_id'].isin(overlapping_matches_list)].reset_index(drop=True)

print(f"Overlapping matches: {len(overlapping_matches_list)}")
print(f"Εγγραφές μετά την αφαίρεση: {len(us_shots)}")

Αρχικές εγγραφές us_shots: 605446
Overlapping matches: 1576
Εγγραφές μετά την αφαίρεση: 566725

Drop 'match_id' from DataFrames

In [5]:
us_shots.drop(['match_id'], axis=1, inplace=True)
sb_shots.drop(['match_id'], axis=1, inplace=True)

print(f"{list(us_shots)} και {list(sb_shots)}")

['x_loc', 'y_loc', 'distance_to_goal', 'angle_to_goal', 'is_goal'] και ['x_loc', 'y_loc', 'distance_to_goal', 'angle_to_goal', 'is_goal']

Merge 2 dataframes

In [6]:
shots = pd.concat([us_shots, sb_shots], ignore_index=True)
print(f"Μέγεθος Understat: {len(us_shots)}")
print(f"Μέγεθος StatsBomb: {len(sb_shots)}")
print(f"Μέγεθος Συνολικό : {len(shots)}")

Μέγεθος Understat: 566725
Μέγεθος StatsBomb: 55857
Μέγεθος Συνολικό : 622582

In [7]:
shots.dtypes

x_loc               float64
y_loc               float64
distance_to_goal    float64
angle_to_goal       float64
is_goal               int64
dtype: object

In [7]:
from sklearn.metrics import log_loss, roc_auc_score, brier_score_loss
import numpy as np

all_results = []

def evaluate_model(y_true, y_pred, model_name="Model"):
    loss = log_loss(y_true, y_pred)
    auc = roc_auc_score(y_true, y_pred)
    brier = brier_score_loss(y_true, y_pred)
    actual_goals = int(np.sum(y_true))
    expected_goals = float(np.sum(y_pred))

    print(f"╔{'═'*45}╗")
    print(f"  Αποτελέσματα για: {model_name}")
    print(f"╠{'═'*45}╣")
    print(f"  Log Loss:        {loss:.4f}")
    print(f"  ROC AUC:         {auc:.4f}")
    print(f"  Brier Score:     {brier:.4f}")
    print(f"  Actual Goals:    {actual_goals}")
    print(f"  Expected Goals:  {expected_goals:.1f}")
    print(f"╚{'═'*45}╝\n")

    return {
        "Model": model_name,
        "Log Loss": round(loss, 4),
        "ROC AUC": round(auc, 4),
        "Brier Score": round(brier, 4),
        "Actual Goals": actual_goals,
        "Expected Goals": round(expected_goals, 1)
    }

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict, StratifiedKFold

X = shots.drop(columns=['is_goal'])
y = shots['is_goal']

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

BL3.1.1.1 — Default Params + Imbalance: None + Calibration: None

In [9]:
bl3_1_1_1 = RandomForestClassifier(
    n_jobs=-1,
    random_state=42
)

predictions_bl3_1_1_1 = cross_val_predict(
    bl3_1_1_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_1_1, model_name="BL3.1.1.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.1.1
╠═════════════════════════════════════════════╣
  Log Loss:        1.0268
  ROC AUC:         0.6729
  Brier Score:     0.0916
  Actual Goals:    60584
  Expected Goals:  60966.6
╚═════════════════════════════════════════════╝

BL3.1.1.2 — Default Params + Imbalance: None + Calibration: Platt Scaling

In [10]:
from sklearn.linear_model import LogisticRegression

P_raw = predictions_bl3_1_1_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_1_1_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_1_2, model_name="BL3.1.1.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.1.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.3000
  ROC AUC:         0.6724
  Brier Score:     0.0834
  Actual Goals:    60584
  Expected Goals:  60619.2
╚═════════════════════════════════════════════╝

BL3.1.1.3 — Default Params + Imbalance: None + Calibration: Isotonic Regression

In [11]:
from sklearn.isotonic import IsotonicRegression

iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_1_1_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_1_1_3, model_name="BL3.1.1.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.1.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2983
  ROC AUC:         0.6721
  Brier Score:     0.0830
  Actual Goals:    60584
  Expected Goals:  60583.0
╚═════════════════════════════════════════════╝

BL3.1.2.1 — Default Params + Imbalance: Class Weight + Calibration: None

In [12]:
bl3_1_2_1 = RandomForestClassifier(
    class_weight='balanced',
    n_jobs=-1,
    random_state=42
)

predictions_bl3_1_2_1 = cross_val_predict(
    bl3_1_2_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_2_1, model_name="BL3.1.2.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.2.1
╠═════════════════════════════════════════════╣
  Log Loss:        1.1075
  ROC AUC:         0.6778
  Brier Score:     0.1896
  Actual Goals:    60584
  Expected Goals:  170772.3
╚═════════════════════════════════════════════╝

BL3.1.2.2 — Default Params + Imbalance: Class Weight + Calibration: Platt Scaling

In [13]:
P_raw = predictions_bl3_1_2_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_1_2_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_2_2, model_name="BL3.1.2.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.2.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.3012
  ROC AUC:         0.6777
  Brier Score:     0.0842
  Actual Goals:    60584
  Expected Goals:  60581.6
╚═════════════════════════════════════════════╝

BL3.1.2.3 — Default Params + Imbalance: Class Weight + Calibration: Isotonic Regression

In [14]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_1_2_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_1_2_3, model_name="BL3.1.2.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.2.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2993
  ROC AUC:         0.6774
  Brier Score:     0.0837
  Actual Goals:    60584
  Expected Goals:  60582.7
╚═════════════════════════════════════════════╝

BL3.1.3.1 — Default Params + Imbalance: Undersampling + Calibration: None

In [15]:
from imblearn.pipeline import make_pipeline as make_imb_pipeline
from imblearn.under_sampling import RandomUnderSampler

bl3_1_3_1 = make_imb_pipeline(
    RandomUnderSampler(random_state=42),
    RandomForestClassifier(
        n_jobs=-1,
        random_state=42
    )
)

predictions_bl3_1_3_1 = cross_val_predict(
    bl3_1_3_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_3_1, model_name="BL3.1.3.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.3.1
╠═════════════════════════════════════════════╣
  Log Loss:        1.1262
  ROC AUC:         0.6823
  Brier Score:     0.2522
  Actual Goals:    60584
  Expected Goals:  263208.2
╚═════════════════════════════════════════════╝

BL3.1.3.2 — Default Params + Imbalance: Undersampling + Calibration: Platt Scaling

In [16]:
from sklearn.linear_model import LogisticRegression

P_raw = predictions_bl3_1_3_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_1_3_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_3_2, model_name="BL3.1.3.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.3.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.3007
  ROC AUC:         0.6823
  Brier Score:     0.0842
  Actual Goals:    60584
  Expected Goals:  60590.3
╚═════════════════════════════════════════════╝

BL3.1.3.3 — Default Params + Imbalance: Undersampling + Calibration: Isotonic Regression

In [17]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_1_3_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_1_3_3, model_name="BL3.1.3.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.3.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2984
  ROC AUC:         0.6819
  Brier Score:     0.0834
  Actual Goals:    60584
  Expected Goals:  60585.5
╚═════════════════════════════════════════════╝

BL3.1.4.1 — Default Params + Imbalance: Oversampling + Calibration: None

In [18]:
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import BorderlineSMOTE

bl3_1_4_1 = make_imb_pipeline(
    StandardScaler(),
    BorderlineSMOTE(random_state=42),
    RandomForestClassifier(
        n_jobs=-1,
        random_state=42
    )
)

predictions_bl3_1_4_1 = cross_val_predict(
    bl3_1_4_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_4_1, model_name="BL3.1.4.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.4.1
╠═════════════════════════════════════════════╣
  Log Loss:        1.0820
  ROC AUC:         0.6643
  Brier Score:     0.1287
  Actual Goals:    60584
  Expected Goals:  108269.0
╚═════════════════════════════════════════════╝

BL3.1.4.2 — Default Params + Imbalance: Oversampling + Calibration: Platt Scaling

In [19]:
from sklearn.linear_model import LogisticRegression

P_raw = predictions_bl3_1_4_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_1_4_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_1_4_2, model_name="BL3.1.4.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.4.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.3025
  ROC AUC:         0.6640
  Brier Score:     0.0843
  Actual Goals:    60584
  Expected Goals:  60584.7
╚═════════════════════════════════════════════╝

BL3.1.4.3 — Default Params + Imbalance: Oversampling + Calibration: Isotonic Regression

In [20]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_1_4_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_1_4_3, model_name="BL3.1.4.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.1.4.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.3014
  ROC AUC:         0.6639
  Brier Score:     0.0840
  Actual Goals:    60584
  Expected Goals:  60583.7
╚═════════════════════════════════════════════╝

BL3.2.1.1 — HyperParams + Imbalance: None + Calibration: None

In [25]:
import optuna
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_predict, cross_val_score

optuna.logging.set_verbosity(optuna.logging.WARNING)

def objective_rf(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 300, step=100),
        'max_depth': trial.suggest_int('max_depth', 4, 16),
        'max_leaf_nodes': trial.suggest_int('max_leaf_nodes', 15, 500, log=True),
        'min_samples_leaf': trial.suggest_int('min_samples_leaf', 10, 500, log=True),
        'max_features': trial.suggest_categorical('max_features', ['sqrt', None]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'log_loss']),
        'n_jobs': -1,
        'random_state': 42
    }

    model = RandomForestClassifier(**params)

    scores = cross_val_score(model, X, y, cv=5, scoring='neg_log_loss')
    return -scores.mean()

sampler = optuna.samplers.TPESampler(seed=42)
study_rf = optuna.create_study(direction='minimize', sampler=sampler)

print("Έναρξη Optuna Tuning για Random Forest...")
study_rf.optimize(objective_rf, n_trials=100, show_progress_bar=True)

print("\nΒέλτιστες Παράμετροι:", study_rf.best_params)
print(f"Καλύτερο CV Log Loss: {study_rf.best_value:.5f}")

best_model_bl3_2_1_1 = RandomForestClassifier(
    **study_rf.best_params,
    n_jobs=-1,
    random_state=42
)

predictions_bl3_2_1_1 = cross_val_predict(
    best_model_bl3_2_1_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_1_1, model_name="BL3.2.1.1")
all_results.append(res)

Έναρξη Optuna Tuning για Random Forest...

Best trial: 96. Best value: 0.279445: 100%|██████████| 100/100 [8:19:46<00:00, 299.87s/it]

Βέλτιστες Παράμετροι: {'n_estimators': 300, 'max_depth': 16, 'max_leaf_nodes': 315, 'min_samples_leaf': 10, 'max_features': None, 'criterion': 'log_loss'}
Καλύτερο CV Log Loss: 0.27944
╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.1.1
╠═════════════════════════════════════════════╣
  Log Loss:        0.2792
  ROC AUC:         0.7465
  Brier Score:     0.0788
  Actual Goals:    60584
  Expected Goals:  60570.9
╚═════════════════════════════════════════════╝

BL3.2.1.2 — HyperParams + Imbalance: None + Calibration: Platt Scaling

In [26]:
P_raw = predictions_bl3_2_1_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_2_1_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_1_2, model_name="BL3.2.1.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.1.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.2845
  ROC AUC:         0.7465
  Brier Score:     0.0797
  Actual Goals:    60584
  Expected Goals:  60580.9
╚═════════════════════════════════════════════╝

BL3.2.1.3 — HyperParams + Imbalance: None + Calibration: Isotonic Regression

In [27]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_2_1_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_2_1_3, model_name="BL3.2.1.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.1.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2793
  ROC AUC:         0.7460
  Brier Score:     0.0788
  Actual Goals:    60584
  Expected Goals:  60587.2
╚═════════════════════════════════════════════╝

BL3.2.2.1 — HyperParams + Imbalance: Class Weight + Calibration: None

In [29]:
bl3_2_2_1 = RandomForestClassifier(
    # Χρησιμοποίηση των βέλτιστων παραμέτρων που βρήκαμε νωρίτερα
    **study_rf.best_params,
    class_weight='balanced',
    random_state=42
)

predictions_bl3_2_2_1 = cross_val_predict(
    bl3_2_2_1,
    X,
    y,
    cv=skf,
    method='predict_proba',
    n_jobs=-1
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_2_1, model_name="BL3.2.2.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.2.1
╠═════════════════════════════════════════════╣
  Log Loss:        0.5839
  ROC AUC:         0.7455
  Brier Score:     0.2007
  Actual Goals:    60584
  Expected Goals:  261787.9
╚═════════════════════════════════════════════╝

BL3.2.2.2 — HyperParams + Imbalance: Class Weight + Calibration: Platt Scaling

In [30]:
P_raw = predictions_bl3_2_2_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_2_2_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_2_2, model_name="BL3.2.2.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.2.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.2806
  ROC AUC:         0.7455
  Brier Score:     0.0793
  Actual Goals:    60584
  Expected Goals:  60578.8
╚═════════════════════════════════════════════╝

BL3.2.2.3 — HyperParams + Imbalance: Class Weight + Calibration: Isotonic Regression

In [31]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_2_2_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_2_2_3, model_name="BL3.2.2.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.2.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2796
  ROC AUC:         0.7450
  Brier Score:     0.0789
  Actual Goals:    60584
  Expected Goals:  60591.9
╚═════════════════════════════════════════════╝

BL3.2.3.1 — HyperParams + Imbalance: Undersampling + Calibration: None

In [32]:
from imblearn.pipeline import make_pipeline as make_imb_pipeline
from imblearn.under_sampling import RandomUnderSampler

bl3_2_3_1 = make_imb_pipeline(
    RandomUnderSampler(random_state=42),
    RandomForestClassifier(
        **study_rf.best_params,
        n_jobs=-1,
        random_state=42
    )
)

predictions_bl3_2_3_1 = cross_val_predict(
    bl3_2_3_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_3_1, model_name="BL3.2.3.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.3.1
╠═════════════════════════════════════════════╣
  Log Loss:        0.5899
  ROC AUC:         0.7449
  Brier Score:     0.2030
  Actual Goals:    60584
  Expected Goals:  264110.3
╚═════════════════════════════════════════════╝

BL3.2.3.2 — HyperParams + Imbalance: Undersampling + Calibration: Platt Scaling

In [33]:
P_raw = predictions_bl3_2_3_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_2_3_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_3_2, model_name="BL3.2.3.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.3.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.2807
  ROC AUC:         0.7449
  Brier Score:     0.0793
  Actual Goals:    60584
  Expected Goals:  60559.3
╚═════════════════════════════════════════════╝

BL3.2.3.3 — HyperParams + Imbalance: Undersampling + Calibration: Isotonic Regression

In [34]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_2_3_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_2_3_3, model_name="BL3.2.3.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.3.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2801
  ROC AUC:         0.7443
  Brier Score:     0.0790
  Actual Goals:    60584
  Expected Goals:  60575.8
╚═════════════════════════════════════════════╝

BL3.2.4.1 — HyperParams + Imbalance: Oversampling + Calibration: None

In [35]:
bl3_2_4_1 = make_imb_pipeline(
    StandardScaler(),
    BorderlineSMOTE(random_state=42),
    RandomForestClassifier(
        **study_rf.best_params,
        n_jobs=-1,
        random_state=42
    )
)

predictions_bl3_2_4_1 = cross_val_predict(
    bl3_2_4_1,
    X,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_4_1, model_name="BL3.2.4.1")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.4.1
╠═════════════════════════════════════════════╣
  Log Loss:        0.5818
  ROC AUC:         0.7439
  Brier Score:     0.2024
  Actual Goals:    60584
  Expected Goals:  257641.2
╚═════════════════════════════════════════════╝

BL3.2.4.2 — HyperParams + Imbalance: Oversampling + Calibration: Platt Scaling

In [36]:
P_raw = predictions_bl3_2_4_1.reshape(-1, 1)

platt_calibrator = LogisticRegression(penalty=None, solver='lbfgs', random_state=42)

predictions_bl3_2_4_2 = cross_val_predict(
    platt_calibrator,
    P_raw,
    y,
    cv=skf,
    method='predict_proba'
)[:, 1]

res = evaluate_model(y, predictions_bl3_2_4_2, model_name="BL3.2.4.2")
all_results.append(res)

C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(
C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\linear_model\_logistic.py:1403: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', l1_ratio set to a float between 0 and 1 instead of penalty='elasticnet', and C=np.inf instead of penalty=None.
  warnings.warn(

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.4.2
╠═════════════════════════════════════════════╣
  Log Loss:        0.2828
  ROC AUC:         0.7439
  Brier Score:     0.0801
  Actual Goals:    60584
  Expected Goals:  60587.4
╚═════════════════════════════════════════════╝

BL3.2.4.3 — HyperParams + Imbalance: Oversampling + Calibration: Isotonic Regression

In [37]:
iso_calibrator = IsotonicRegression(y_min=0.0, y_max=1.0, out_of_bounds='clip')

predictions_bl3_2_4_3 = cross_val_predict(
    iso_calibrator,
    P_raw,
    y,
    cv=skf
)

res = evaluate_model(y, predictions_bl3_2_4_3, model_name="BL3.2.4.3")
all_results.append(res)

╔═════════════════════════════════════════════╗
  Αποτελέσματα για: BL3.2.4.3
╠═════════════════════════════════════════════╣
  Log Loss:        0.2813
  ROC AUC:         0.7432
  Brier Score:     0.0794
  Actual Goals:    60584
  Expected Goals:  60793.4
╚═════════════════════════════════════════════╝

Export Results to csv

In [38]:
df_results = pd.DataFrame(all_results)

for col in ['model_name', 'Model', 'model']:
    if col in df_results.columns:
        df_results = df_results.drop_duplicates(subset=[col], keep='last')
        break

df_results.to_csv('BL3-results.csv', index=False, encoding='utf-8-sig')
display(df_results)

        Model  Log Loss  ROC AUC  Brier Score  Actual Goals  Expected Goals
0   BL3.1.1.1    1.0268   0.6729       0.0916         60584         60966.6
1   BL3.1.1.2    0.3000   0.6724       0.0834         60584         60619.2
2   BL3.1.1.3    0.2983   0.6721       0.0830         60584         60583.0
3   BL3.1.2.1    1.1075   0.6778       0.1896         60584        170772.3
4   BL3.1.2.2    0.3012   0.6777       0.0842         60584         60581.6
5   BL3.1.2.3    0.2993   0.6774       0.0837         60584         60582.7
6   BL3.1.3.1    1.1262   0.6823       0.2522         60584        263208.2
7   BL3.1.3.2    0.3007   0.6823       0.0842         60584         60590.3
8   BL3.1.3.3    0.2984   0.6819       0.0834         60584         60585.5
9   BL3.1.4.1    1.0820   0.6643       0.1287         60584        108269.0
10  BL3.1.4.2    0.3025   0.6640       0.0843         60584         60584.7
11  BL3.1.4.3    0.3014   0.6639       0.0840         60584         60583.7
12  BL3.2.1.1    0.2792   0.7465       0.0788         60584         60570.9
13  BL3.2.1.2    0.2845   0.7465       0.0797         60584         60580.9
14  BL3.2.1.3    0.2793   0.7460       0.0788         60584         60587.2
15  BL3.2.2.1    0.5839   0.7455       0.2007         60584        261787.9
16  BL3.2.2.2    0.2806   0.7455       0.0793         60584         60578.8
17  BL3.2.2.3    0.2796   0.7450       0.0789         60584         60591.9
18  BL3.2.3.1    0.5899   0.7449       0.2030         60584        264110.3
19  BL3.2.3.2    0.2807   0.7449       0.0793         60584         60559.3
20  BL3.2.3.3    0.2801   0.7443       0.0790         60584         60575.8
21  BL3.2.4.1    0.5818   0.7439       0.2024         60584        257641.2
22  BL3.2.4.2    0.2828   0.7439       0.0801         60584         60587.4
23  BL3.2.4.3    0.2813   0.7432       0.0794         60584         60793.4

Model Training

In [8]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_predict

X = shots.drop(columns=['is_goal'])
y = shots['is_goal']

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

model = RandomForestClassifier()
predictions = cross_val_predict(model, X, y, cv=skf, method='predict_proba', n_jobs=-1)[:, 1]

Metrics

In [9]:
from sklearn.metrics import log_loss, roc_auc_score, brier_score_loss

print("Default Random Forest settings, 1shot/leaf, overfitting")
print(f"Log Loss: {log_loss(y, predictions):.4f}")
print(f"ROC AUC:  {roc_auc_score(y, predictions):.4f}")
print(f"Brier Score:  {brier_score_loss(y, predictions):.04f}")

Default Random Forest settings, 1shot/leaf, overfitting
Log Loss: 1.0264
ROC AUC:  0.6731
Brier Score:  0.0916

Finding the best params

In [13]:
"""
# απειρες ωρες
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

model2 = RandomizedSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=1),
    param_distributions = {
        'n_estimators': [200],
        'max_depth': [5, 8, 10],
        'min_samples_split': [100, 200],
        'min_samples_leaf': [50, 100, 200],
        'max_features': ['sqrt', None]
    },
    scoring = 'neg_log_loss',
    cv = skf,
    n_iter=20,
    random_state = 42,
    verbose=2,
    n_jobs = -1
)

model2.fit(X, y)

print(f"{model2.best_params_}")
# Best Params:
#
"""

Fitting 10 folds for each of 20 candidates, totalling 200 fits

KeyboardInterrupt:

In [10]:
"""
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV

model2 = RandomizedSearchCV(
    RandomForestClassifier(random_state=42, n_jobs=1),
    param_distributions = {
        'n_estimators': [100, 200],
        'max_depth': [5, 8, 10],
        'min_samples_split': [100, 200],
        'min_samples_leaf': [50, 100, 200],
        'max_features': ['sqrt']
    },
    scoring = 'neg_log_loss',
    cv = 3,
    n_iter=10,
    random_state = 42,
    verbose=2,
    n_jobs = 4
)

model2.fit(X, y)

print(f"{model2.best_params_}")
# Best Params:
# me 3 folds, oxi skf
# {'n_estimators': 200, 'min_samples_split': 100, 'min_samples_leaf': 50, 'max_features': 'sqrt', 'max_depth': 8}
"""

Fitting 3 folds for each of 10 candidates, totalling 30 fits
{'n_estimators': 200, 'min_samples_split': 100, 'min_samples_leaf': 50, 'max_features': 'sqrt', 'max_depth': 8}

In [15]:
import optuna
from optuna.samplers import TPESampler
from sklearn.model_selection import cross_val_predict, cross_val_score


def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=100),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_split': trial.suggest_int("min_samples_split", 2, 50),
        'min_samples_leaf': trial.suggest_int("min_samples_leaf", 1, 50),
        'max_features': trial.suggest_categorical("max_features", ['sqrt', None]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'log_loss']),
        'random_state': 42
    }

    model2 = RandomForestClassifier(**params)
    scores = cross_val_score(model2, X, y, cv=skf, scoring='neg_log_loss', n_jobs=-1)
    return -scores.mean()

study = optuna.create_study(
    direction='minimize',
    sampler = TPESampler(seed=42)
)

study.optimize(objective, n_trials=100)

[I 2026-09-07 05:21:03,808] A new study created in memory with name: no-name-d6c7cdaf-f74f-4981-a722-cac367cf56ed
[W 2026-09-07 05:34:03,343] Trial 0 failed with parameters: {'n_estimators': 400, 'max_depth': 29, 'min_samples_split': 37, 'min_samples_leaf': 30, 'max_features': 'sqrt', 'criterion': 'log_loss'} because of the following error: KeyboardInterrupt().
Traceback (most recent call last):
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\optuna\study\_optimize.py", line 206, in _run_trial
    value_or_values = func(trial)
                      ^^^^^^^^^^^
  File "C:\Users\Zoe\AppData\Local\Temp\ipykernel_18260\4263610211.py", line 18, in objective
    scores = cross_val_score(model2, X, y, cv=skf, scoring='neg_log_loss', n_jobs=-1)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 650, in cross_val_score
    cv_results = cross_validate(
                 ^^^^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\utils\_param_validation.py", line 218, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\model_selection\_validation.py", line 372, in cross_validate
    results = parallel(
              ^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\sklearn\utils\parallel.py", line 91, in __call__
    return super().__call__(iterable_with_config_and_warning_filters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\joblib\parallel.py", line 2072, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\joblib\parallel.py", line 1682, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\Zoe\PycharmProjects\thesis\.venv\Lib\site-packages\joblib\parallel.py", line 1800, in _retrieve
    time.sleep(0.01)
KeyboardInterrupt
[W 2026-09-07 05:34:03,346] Trial 0 failed with value None.

KeyboardInterrupt:

In [12]:
print(f"Best Log Loss: {study.best_value:.4f}")
print(f"Best Params: {study.best_params}")

Best Log Loss: 1.0281
Best Params: {'n_estimators': 700, 'max_depth': 17, 'min_samples_split': 30, 'min_samples_leaf': 2, 'max_features': 0.7819459112971967, 'criterion': 'gini'}

In [ ]:
from optuna.visualization import (
    plot_optimization_history,
    plot_param_importances,
    plot_contour
)

plot_optimization_history(study)
plot_param_importances(study)
plot_contour(study, params=['max_depth', 'n_estimators'])

Με pruning

In [ ]:
from optuna.pruners import MedianPruner


def objective(trial):
    params = {
        'n_estimators': trial.suggest_int('n_estimators', 100, 1000, step=100),
        'max_depth': trial.suggest_int('max_depth', 3, 30),
        'min_samples_split': trial.suggest_int("min_samples_split", 2, 50),
        'min_samples_leaf': trial.suggest_int("min_samples_leaf", 1, 50),
        'max_features': trial.suggest_categorical("max_features", ['sqrt', None]),
        'criterion': trial.suggest_categorical('criterion', ['gini', 'log_loss']),
        'random_state': 42
    }

    model = RandomForestClassifier(**params)
    fold_scores = []
    for step, (train_idx, val_idx) in enumerate(skf.split(X, y)):
        model.fit(X.iloc[train_idx], y.iloc[train_idx])
        score = log_loss(y.iloc[val_idx], model.predict_proba(X.iloc[val_idx]))
        fold_scores.append(score)

        trial.report(np.mean(fold_scores), step)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()
    return np.mean(fold_scores)

study = optuna.create_study(
    direction='minimize',
    sampler=TPESampler(seed=42),
    pruner=MedianPruner(n_startup_trials=5, n_warmup_steps=2)
)
study.optimize(objective, n_trials=100)